### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shivam0x** [JosephusZhou/InsDownload#1]
Even after logging into the webview not able to download anything. Not getting any option to download. Just instagram inside webview.

**Comment by JosephusZhou** [comment]
> Even after logging into the webview not able to download anything. Not getting any option to download. Just instagram inside webview.

After logging into instgram, did you get cookies？Is there a redirect to the post link which you want to download after logging into the webview？

The post link is like to "https://www.instagram.com/p/CBsNXQ4FoAd/?igshid=1kofrunspiorr".
